version: "3.9"

services:
  backend:
    build: .
    container_name: schooltrack_backend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app:cached
    networks:
      - schooltrack_net

  mongo:
    image: mongo:6.0
    container_name: schooltrack_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - schooltrack_net

  redis:
    image: redis:7
    container_name: schooltrack_redis
    restart: always
    networks:
      - schooltrack_net

networks:
  schooltrack_net:

volumes:
  mongo_data:
